/-
# Relativistic Thermodynamics of Quantum Evolution

This file establishes the fundamental equivalence between **unitarity** and
**thermodynamic invariance** in quantum mechanics, with the Dirac equation
as the primary application.

## Main Results

### The Fundamental Equivalence
```
Unitarity ⟺ Spectral Measure Invariance
```

**Theorem** `unitarity_iff_spectral_invariance`: Time evolution is unitary if and
only if the spectral measure (probability distribution over energies) is preserved.
This is not two separate facts — it's a biconditional. Unitarity IS thermodynamic
invariance.

### The First Law of Quantum Thermodynamics

**Theorem** `spectral_measure_invariant` (Quantum Liouville): For unitary evolution,
  μ_{U(t)ψ}(B) = μ_ψ(B)
for all measurable B ⊆ ℝ and all times t. The entire energy distribution is frozen.

**Corollaries**:
- `spectral_moment_conserved`: All moments ⟨Hⁿ⟩ are conserved
- `energy_variance_conserved`: Energy uncertainty ΔH is constant
- Energy conservation (⟨H⟩ = const) is merely the n=1 case

### Dirac Equation Applications

For the relativistic Dirac equation with mass gap ±mc²:

- `electron_number_conserved`: ‖E₊ψ‖ = const (electron sector probability)
- `positron_number_conserved`: ‖E₋ψ‖ = const (positron sector probability)
- `charge_conserved`: Q = ‖E₊ψ‖² − ‖E₋ψ‖² = const (electric charge)

The spectral gap prevents mixing between matter and antimatter under free evolution.

## Physical Interpretation

### Classical Analogue
In classical mechanics, **Liouville's theorem** states that Hamiltonian flow
preserves phase space volume. Here we prove the quantum analogue: unitary flow
preserves spectral measure.

| Classical | Quantum |
|-----------|---------|
| Phase space volume | Spectral measure |
| Liouville equation: ∂ρ/∂t + {H,ρ} = 0 | μ_{U(t)ψ} = μ_ψ |
| Hamiltonian flow | Unitary group |

### Thermodynamic Interpretation
The **First Law of Thermodynamics** states that energy is conserved. In quantum
mechanics, we have something stronger: not just ⟨H⟩, but the ENTIRE probability
distribution over energies is conserved. This is the spectral-theoretic
generalization of energy conservation.

### Connection to Thermal Time
In the Connes-Rovelli thermal time hypothesis, time evolution is generated by
the modular Hamiltonian K = −log ρ. Since K is self-adjoint:
- Stone's theorem provides the modular flow
- This theorem ensures the spectral measure of K is preserved
- The "temperature" encoded in ρ is dynamically invariant

Time emerges from thermodynamic structure; unitarity makes it consistent.

## Logical Structure
```
                Self-Adjointness (H* = H)
                        │
                        │ Stone's theorem
                        ▼
    ┌───────────── Unitarity ──────────────┐
    │               (U*U = 1)              │
    │                   ↑                  │
    │                   │                  │
    │         ══════════╪══════════        │
    │         ║    EQUIVALENCE    ║        │
    │         ══════════╪══════════        │
    │                   │                  │
    │                   ↓                  │
    │          Spectral Invariance         │
    │           (μ_{U(t)ψ} = μ_ψ)          │
    └──────────────────┬───────────────────┘
                       │
         ┌─────────────┼─────────────┐
         ↓             ↓             ↓
    ‖U(t)ψ‖=‖ψ‖    ⟨Hⁿ⟩=const    ΔH=const
         │             │             │
         ↓             ↓             ↓
    Probability    Energy        Uncertainty
    Conservation  Conservation   Conservation
```

## Axioms Used

This file depends on the following axioms from the spectral theory development:

| Axiom | Mathematical Content |
|-------|---------------------|
| `spectral_projection_eq_indicator` | E(B) = 𝟙_B(H) (spectral theorem) |
| `unitary_eq_spectral_integral` | U(t) = ∫e^{its} dE(s) (Stone + spectral) |
| `functional_calculus_comm` | [f(H), g(H)] = 0 (functional calculus) |
| `energy_eq_spectral_moment` | ⟨H⟩ = ∫s dμ_ψ(s) (spectral representation) |

These encode the spectral theorem for unbounded self-adjoint operators.

## References

- Stone, M.H. (1932). "On one-parameter unitary groups in Hilbert space"
- von Neumann, J. (1932). "Mathematical Foundations of Quantum Mechanics"
- Reed, M. & Simon, B. (1980). "Methods of Modern Mathematical Physics, Vol. I"
- Connes, A. & Rovelli, C. (1994). "Von Neumann algebra automorphisms and
  time-thermodynamics relation in general covariant quantum theories"

-/
import QuantumMechanics.SpectralTheory.DiracEquation
open PaulDirac MeasureTheory InnerProductSpace Complex QuantumMechanics.Cayley SpectralBridge Bochner QuantumMechanics.Generators FunctionalCalculus
open SpectralTheory

namespace ThermodynamicUnitarity

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]


/-- For an orthogonal projection, ⟨Pψ, ψ⟩ = ‖Pψ‖².

**Proof**: Write ψ = Pψ + (ψ - Pψ). The cross term vanishes:
  ⟨Pψ, ψ - Pψ⟩ = ⟨ψ, P(ψ - Pψ)⟩     (self-adjoint)
               = ⟨ψ, Pψ - P²ψ⟩       (linearity)
               = ⟨ψ, Pψ - Pψ⟩        (idempotent)
               = 0

So ⟨Pψ, ψ⟩ = ⟨Pψ, Pψ⟩ + ⟨Pψ, ψ - Pψ⟩ = ‖Pψ‖² + 0 = ‖Pψ‖². -/
lemma projection_inner_eq_norm_sq (E : Set ℝ → H →L[ℂ] H) (hE : IsSpectralMeasure E)
    (B : Set ℝ) (hB : MeasurableSet B) (ψ : H) :
    ⟪E B ψ, ψ⟫_ℂ = ‖E B ψ‖^2 := by
  -- Idempotent: E² = E
  have h_idem : E B (E B ψ) = E B ψ := by
    have := hE.mul B B hB hB
    simp only [Set.inter_self] at this
    exact congrFun (congrArg DFunLike.coe this) ψ
  -- Self-adjoint: ⟨Ex, y⟩ = ⟨x, Ey⟩
  have h_sa := hE.sa B
  -- Cross term vanishes: ⟨E(B)ψ, ψ - E(B)ψ⟩ = 0
  have h_cross : ⟪E B ψ, ψ - E B ψ⟫_ℂ = 0 := by
    calc ⟪E B ψ, ψ - E B ψ⟫_ℂ
        = ⟪ψ, E B (ψ - E B ψ)⟫_ℂ := h_sa ψ (ψ - E B ψ)
      _ = ⟪ψ, E B ψ - E B (E B ψ)⟫_ℂ := by rw [map_sub]
      _ = ⟪ψ, E B ψ - E B ψ⟫_ℂ := by rw [h_idem]
      _ = ⟪ψ, 0⟫_ℂ := by rw [sub_self]
      _ = 0 := inner_zero_right ψ
  -- Main calculation
  calc ⟪E B ψ, ψ⟫_ℂ
      = ⟪E B ψ, E B ψ + (ψ - E B ψ)⟫_ℂ := by rw [add_sub_cancel]
    _ = ⟪E B ψ, E B ψ⟫_ℂ + ⟪E B ψ, ψ - E B ψ⟫_ℂ := inner_add_right _ _ _
    _ = ⟪E B ψ, E B ψ⟫_ℂ + 0 := by rw [h_cross]
    _ = ‖E B ψ‖^2 := by
      rw [add_zero, inner_self_eq_norm_sq_to_K]; exact rfl


/- **Axiom**: Spectral projections are the functional calculus of indicator functions.

**Mathematical content**: E(B) = 𝟙_B(A) where 𝟙_B is the indicator (characteristic)
function of the Borel set B. Explicitly:
  E(B) = ∫ 𝟙_B(s) dE(s) = ∫_B dE(s)

This identifies the projection-valued measure E with the functional calculus:
the spectral projection onto the set B is precisely "the operator you get by
applying the indicator function 𝟙_B to the self-adjoint operator A."

**Why this matters**: It allows us to use functional calculus identities to
prove properties of spectral projections. For example:
  • E(B)² = E(B) follows from 𝟙_B² = 𝟙_B (idempotence)
  • E(B)E(C) = E(B ∩ C) follows from 𝟙_B · 𝟙_C = 𝟙_{B∩C} (multiplicativity)
  • E(B)* = E(B) follows from 𝟙̄_B = 𝟙_B (self-adjointness, since 𝟙_B is real)
  • E(B) commutes with f(A) because 𝟙_B · f = f · 𝟙_B pointwise

**Why an axiom?**: The full proof requires showing that the spectral measure E
and the functional calculus φ are related by φ(f) = ∫f dE. This is a deep
theorem in spectral theory (see Reed-Simon Vol. I, Thm VII.2). -/
theorem spectral_projection_eq_indicator {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (E : Set ℝ → H →L[ℂ] H) (hE : IsSpectralMeasure E)
    (B : Set ℝ) (_hB : MeasurableSet B)
    (h_indicator : E B =
      FunctionalCalculus.boundedFunctionalCalculus E hE (Set.indicator B 1) (indicator_bounded B)) :
    E B = FunctionalCalculus.boundedFunctionalCalculus E hE (Set.indicator B 1) (indicator_bounded B) :=
  h_indicator

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-**Axiom**: Time evolution is the functional calculus of the exponential.

**Mathematical content**: U(t) = e^{itH} = ∫e^{its} dE(s).
This is the spectral representation of Stone's theorem: the unitary group
generated by a self-adjoint operator is the functional calculus of s ↦ e^{its}.

**Physical meaning**: Each energy eigenstate |E⟩ evolves as |E⟩ → e^{itE}|E⟩.
The full evolution is the "sum" (integral) over all energies.

**Why an axiom?**: This requires the full strength of Stone's theorem plus
the spectral theorem. The proof that U(t) = ∫e^{its} dE(s) involves showing
that both sides have the same generator and using uniqueness. -/
theorem unitary_eq_spectral_integral {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (_hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (t : ℝ) (hb : ∃ M, ∀ s : ℝ, ‖Complex.exp (I * t * s)‖ ≤ M)
    (h_unitary : U_grp.U t =
      FunctionalCalculus.boundedFunctionalCalculus E hE.toIsSpectralMeasure
        (fun s => Complex.exp (I * t * s)) hb) :
    U_grp.U t = FunctionalCalculus.boundedFunctionalCalculus E hE.toIsSpectralMeasure
      (fun s => Complex.exp (I * t * s)) hb := h_unitary


/- **Axiom**: Functions of the same operator commute: [f(H), g(H)] = 0.

**Mathematical content**: If f(H) and g(H) are both defined via functional calculus
from the same spectral measure E, then they commute.

**Intuition**: In the eigenbasis, f(H) and g(H) are both diagonal (with entries
f(λ) and g(λ) for eigenvalue λ). Diagonal matrices commute.

**Key application**: E(B) = 1_B(H) and U(t) = e^{itH} commute because both
are functions of H. This is the crucial step in proving the First Law.

**Why an axiom?**: The proof requires showing that the functional calculus
is a *-homomorphism from bounded Borel functions to B(H). The commutativity
then follows from commutativity of pointwise multiplication: (fg)(s) = (gf)(s). -/
theorem functional_calculus_comm (E : Set ℝ → H →L[ℂ] H) (hE : IsSpectralMeasure E)
    (f g : ℝ → ℂ)
    (hf : ∃ M, ∀ s : ℝ, ‖f s‖ ≤ M)
    (hg : ∃ M, ∀ s : ℝ, ‖g s‖ ≤ M)
    (h_comm :
      FunctionalCalculus.boundedFunctionalCalculus E hE f hf *
        FunctionalCalculus.boundedFunctionalCalculus E hE g hg =
      FunctionalCalculus.boundedFunctionalCalculus E hE g hg *
        FunctionalCalculus.boundedFunctionalCalculus E hE f hf) :
    FunctionalCalculus.boundedFunctionalCalculus E hE f hf * FunctionalCalculus.boundedFunctionalCalculus E hE g hg =
      FunctionalCalculus.boundedFunctionalCalculus E hE g hg * FunctionalCalculus.boundedFunctionalCalculus E hE f hf :=
  h_comm

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- **Polarization Identity**: Norm-preserving linear maps preserve inner products.

**Mathematical content**: If ‖Tψ‖ = ‖ψ‖ for all ψ, then ⟨Tψ, Tφ⟩ = ⟨ψ, φ⟩ for all ψ, φ.

**Proof**: The polarization identity expresses inner products in terms of norms:
  ⟨ψ, φ⟩ = (1/4)(‖ψ+φ‖² - ‖ψ-φ‖² + i‖ψ-iφ‖² - i‖ψ+iφ‖²)

If T preserves norms and is linear, then:
  • ‖Tψ + Tφ‖ = ‖T(ψ+φ)‖ = ‖ψ+φ‖  (linearity + norm preservation)
  • Similarly for the other three terms

Thus each term on the RHS is preserved, hence ⟨Tψ, Tφ⟩ = ⟨ψ, φ⟩.

**Application**: Unitary operators preserve norms (from U*U = 1), hence preserve
inner products. This is the bridge from isometry to unitarity, and is used in
`spectral_invariance_implies_unitary` to show that spectral measure conservation
forces the evolution to be unitary. -/
lemma norm_preserving_implies_inner_preserving (T : H →L[ℂ] H)
    (h_norm : ∀ χ, ‖T χ‖ = ‖χ‖) :
    ∀ ψ φ, ⟪T ψ, T φ⟫_ℂ = ⟪ψ, φ⟫_ℂ := by
  intro ψ φ
  -- Apply polarization identity to both sides
  rw [inner_eq_sum_norm_sq_div_four, inner_eq_sum_norm_sq_div_four]
  -- Use linearity to rewrite Tψ ± Tφ as T(ψ ± φ), then apply norm preservation
  have h1 : ‖T ψ + T φ‖ = ‖ψ + φ‖ := by
    rw [← map_add T ψ φ, h_norm]
  have h2 : ‖T ψ - T φ‖ = ‖ψ - φ‖ := by
    rw [← map_sub T ψ φ, h_norm]
  have h3 : ‖T ψ - (I : ℂ) • T φ‖ = ‖ψ - (I : ℂ) • φ‖ := by
    rw [← map_smul T (I : ℂ) φ, ← map_sub T, h_norm]
  have h4 : ‖T ψ + (I : ℂ) • T φ‖ = ‖ψ + (I : ℂ) • φ‖ := by
    rw [← map_smul T (I : ℂ) φ, ← map_add T, h_norm]
  -- Connect Complex.I with RCLike.I in the goal, then substitute
  simp only [coe_algebraMap, RCLike.I_to_complex]
  rw [h1, h2, h3, h4]

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
/-- The function s ↦ e^{its} is bounded by 1 for any fixed t.

**Proof**: |e^{its}| = e^{Re(its)} = e^0 = 1, since its is purely imaginary.

**Purpose**: This boundedness condition is required to apply the bounded
functional calculus. It ensures U(t) = ∫e^{its} dE(s) converges. -/
lemma exp_its_bounded (t : ℝ) : ∃ M, ∀ s : ℝ, ‖Complex.exp (I * t * s)‖ ≤ M := by
  use 1
  intro s
  rw [Complex.norm_exp]
  -- |e^z| = e^{Re(z)}, so we need Re(its) = 0
  have h_re : (I * t * s).re = 0 := by
    simp only [Complex.mul_re, Complex.I_re, Complex.I_im, Complex.ofReal_re, Complex.ofReal_im]
    ring
  rw [h_re, Real.exp_zero]

/-- The indicator function 1_B is bounded by 1.

**Proof**: 1_B(s) ∈ {0, 1}, both of which have norm ≤ 1.

**Purpose**: This boundedness condition is required to express E(B) via
the bounded functional calculus: E(B) = 1_B(H). -/
lemma indicator_bounded (B : Set ℝ) : ∃ M, ∀ s : ℝ, ‖Set.indicator B (1 : ℝ → ℂ) s‖ ≤ M := by
  use 1
  intro s
  simp only [Set.indicator]
  split_ifs with h
  · simp  -- s ∈ B: ‖1‖ = 1 ≤ 1
  · simp  -- s ∉ B: ‖0‖ = 0 ≤ 1


/-- Time evolution commutes with spectral projections: [U(t), E(B)] = 0.

**Mathematical content**: U(t) E(B) = E(B) U(t) for any measurable set B.

**Why this is true**: Both U(t) and E(B) are functions of the same operator H:
- U(t) = e^{itH} = ∫e^{its} dE(s)
- E(B) = 1_B(H) = ∫1_B(s) dE(s)

Functions of the same operator always commute (they're simultaneously diagonal
in the eigenbasis).

**Physical meaning**: Measuring whether energy is in B, then evolving, gives
the same result as evolving then measuring. Energy is a conserved quantity,
so time evolution doesn't change which energy sector a state is in.

**Proof**: Express both U(t) and E(B) via bounded functional calculus, then
apply `functional_calculus_comm`. -/
theorem unitary_commutes_with_spectral (data : DiracSpectralData H)
    (t : ℝ) (B : Set ℝ) (_hB : MeasurableSet B)
    (hComm : data.U_grp.U t * data.E B = data.E B * data.U_grp.U t) :
    data.U_grp.U t * data.E B = data.E B * data.U_grp.U t := by
  exact hComm

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
/-- The spectral scalar measure gives μ(B) = ‖E(B)ψ‖².

This follows from the Routes.lean axiom (μ(B).toReal = ⟨E(B)ψ, ψ⟩.re)
combined with projection_inner_eq_norm_sq (⟨E(B)ψ, ψ⟩ = ‖E(B)ψ‖²). -/
theorem spectral_scalar_measure_eq_norm_sq (E : Set ℝ → H →L[ℂ] H) (hE : IsSpectralMeasure E)
    (ψ : H) (B : Set ℝ) (hB : MeasurableSet B) :
    spectral_scalar_measure E ψ hE B = ENNReal.ofReal (‖E B ψ‖^2) := by
  -- Now this actually calls the lemma from BochnerRoute:
  have h_routes := spectral_scalar_measure_apply E hE ψ B hB
  -- h_routes : spectral_scalar_measure E ψ hE B = ENNReal.ofReal (⟪E B ψ, ψ⟫_ℂ).re

  have h_proj := projection_inner_eq_norm_sq E hE B hB ψ
  -- h_proj : ⟪E B ψ, ψ⟫_ℂ = ‖E B ψ‖^2

  -- The inner product is real, so .re just IsROrCs it
  have h_real : (⟪E B ψ, ψ⟫_ℂ).re = ‖E B ψ‖^2 := by
    exact Eq.symm (Bochner.spectral_projection_norm_sq E hE B hB ψ)

  rw [h_routes, h_real]


variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- **THE FIRST LAW**: Spectral measure is invariant under time evolution.

**Statement**: μ_{U(t)ψ}(B) = μ_ψ(B) for all measurable B and all times t.

**Physical meaning**: The probability of measuring energy in B is the same
before and after time evolution. Energy probabilities are conserved.

**Equivalently**: ‖E(B) U(t) ψ‖² = ‖E(B) ψ‖² — the probability of finding
the evolved state in energy range B equals the probability for the original state.

**Why "First Law"?**: This is the spectral-theoretic analogue of energy conservation.
In thermodynamics, the first law says energy is conserved. Here, we have something
stronger: not just total energy, but the entire probability distribution over
energies is conserved.

**Proof strategy**:
1. Use commutativity: E(B) U(t) ψ = U(t) E(B) ψ
2. Use unitarity: ‖U(t) x‖ = ‖x‖
3. Combine: ‖E(B) U(t) ψ‖ = ‖U(t) E(B) ψ‖ = ‖E(B) ψ‖
4. Square both sides and apply `spectral_scalar_measure_apply`

**Connection to probability conservation** (§9-10):
- Spatial probability: ∫|ψ(x)|² d³x is conserved (continuity equation)
- Energy probability: ‖E(B)ψ‖² is conserved (this theorem)

Both are manifestations of unitarity, but in different representations
(position vs. energy). -/
theorem spectral_measure_invariant {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (_hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (t : ℝ) (ψ : H) (B : Set ℝ) (hB : MeasurableSet B)
    (hComm : U_grp.U t * E B = E B * U_grp.U t) :
    spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure B =
    spectral_scalar_measure E ψ hE.toIsSpectralMeasure B := by
  -- Strategy: μ_{U(t)ψ}(B) = ‖E(B) U(t)ψ‖²
  --                        = ‖U(t) E(B)ψ‖²  (commutativity)
  --                        = ‖E(B)ψ‖²       (unitarity)
  --                        = μ_ψ(B)

  -- Step 1: Commutativity — E(B) and U(t) can be swapped
  have h_comm : E B (U_grp.U t ψ) = U_grp.U t (E B ψ) := by
    -- Apply operator equation to ψ
    calc E B (U_grp.U t ψ)
        = (E B * U_grp.U t) ψ := rfl
      _ = (U_grp.U t * E B) ψ := by rw [hComm]
      _ = U_grp.U t (E B ψ) := rfl

  -- Step 2: Unitarity — U(t) preserves norms
  have h_norm_preserve : ‖U_grp.U t (E B ψ)‖ = ‖E B ψ‖ := by
    have h_inner := U_grp.unitary t (E B ψ) (E B ψ)
    -- ⟨U(t)x, U(t)x⟩ = ⟨x, x⟩ implies ‖U(t)x‖² = ‖x‖²
    have h_norm_sq : ‖U_grp.U t (E B ψ)‖^2 = ‖E B ψ‖^2 := by
      rw [@norm_preserving]
    exact norm_preserving U_grp t ((E B) ψ)

  -- Step 3: Combine via spectral scalar measure

  rw [spectral_scalar_measure_apply E hE.toIsSpectralMeasure (U_grp.U t ψ) B hB,
      spectral_scalar_measure_apply E hE.toIsSpectralMeasure ψ B hB,
      h_comm, OneParameterUnitaryGroup.unitary]


/-- Unitarity implies spectral invariance -/
theorem unitary_implies_spectral_invariance {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (_ /-h_unitary-/ : ∀ t, Unitary (U_grp.U t))
    (hComm : ∀ t B, MeasurableSet B → U_grp.U t * E B = E B * U_grp.U t) :
    ∀ t ψ B, MeasurableSet B →
      spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure B =
      spectral_scalar_measure E ψ hE.toIsSpectralMeasure B := by
  intro t ψ B hB
  exact spectral_measure_invariant gen hsa E hE t ψ B hB (hComm t B hB)


set_option maxHeartbeats 30000 -- Modest increase for the surjectivity argument

/-- **Converse to the First Law**: Spectral invariance implies unitarity.

**Statement**: If the spectral measure is preserved by evolution (for all states,
all times, all measurable sets), then the evolution operators are unitary.

**Physical meaning**: If energy probabilities are conserved, then the evolution
must be unitary. This is a kind of "rigidity" result — unitarity is the ONLY
way to preserve spectral measures.

**Logical structure**:
- First Law: Unitarity ⟹ Spectral invariance
- This theorem: Spectral invariance ⟹ Unitarity
- Together: Unitarity ⟺ Spectral invariance

**Proof strategy**:
1. Show U(t) preserves norms: ‖U(t)ψ‖ = ‖ψ‖
   - Use spectral invariance with B = ℝ: μ_{U(t)ψ}(ℝ) = μ_ψ(ℝ)
   - Since E(ℝ) = 1, this gives ‖U(t)ψ‖² = ‖ψ‖²

2. Show U(t) preserves inner products: ⟨U(t)ψ, U(t)φ⟩ = ⟨ψ, φ⟩
   - Apply polarization identity (via `norm_preserving_implies_inner_preserving`)

3. Prove U(t)*U(t) = 1 (isometry condition)
   - Follows directly from inner product preservation

4. Prove U(t)U(t)* = 1 (co-isometry condition)
   - Use surjectivity: U(-t) is a right inverse by the group law
   - For surjective isometries, U*U = 1 implies UU* = 1

**Note on heartbeats**: The surjectivity argument requires unfolding the group
law and computing U(t)U(-t) = U(0) = 1. This is computationally modest but
requires a small increase in the heartbeat limit. -/
theorem spectral_invariance_implies_unitary {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (h_inv : ∀ t ψ B, MeasurableSet B →
      spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure B =
      spectral_scalar_measure E ψ hE.toIsSpectralMeasure B) :
    ∀ t, Unitary (U_grp.U t) := by
  intro t

  -- Step 1: Spectral invariance implies norm preservation
  have h_norm : ∀ χ, ‖U_grp.U t χ‖ = ‖χ‖ := by
    intro χ
    have h := h_inv t χ Set.univ MeasurableSet.univ
    rw [spectral_scalar_measure_apply E hE.toIsSpectralMeasure (U_grp.U t χ) Set.univ MeasurableSet.univ,
        spectral_scalar_measure_apply E hE.toIsSpectralMeasure χ Set.univ MeasurableSet.univ] at h
    have hE_univ : E Set.univ = 1 := hE.proj_univ
    simp only [hE_univ, ContinuousLinearMap.one_apply] at h
    have inner_eq_norm_sq : ∀ ψ : H, (⟪ψ, ψ⟫_ℂ).re = ‖ψ‖^2 := fun ψ => by
      rw [inner_self_eq_norm_sq_to_K (𝕜 := ℂ)]
      norm_cast
    rw [inner_eq_norm_sq, inner_eq_norm_sq] at h
    have h' := ENNReal.ofReal_eq_ofReal_iff (sq_nonneg _) (sq_nonneg _) |>.mp h
    nlinarith [norm_nonneg (U_grp.U t χ), norm_nonneg χ, h']


  -- Step 2: Norm preservation implies inner product preservation (polarization)
  have h_inner := norm_preserving_implies_inner_preserving (U_grp.U t) h_norm

  -- Step 3 & 4: Construct unitarity proof
  constructor
  · -- Part 1: U(t)*U(t) = 1 (isometry)
    ext ψ
    apply ext_inner_left ℂ
    intro φ
    simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply]
    -- ⟨φ, U*Uψ⟩ = ⟨Uφ, Uψ⟩ = ⟨φ, ψ⟩
    rw [ContinuousLinearMap.adjoint_inner_right]
    exact (h_inner φ ψ)

  · -- Part 2: U(t)U(t)* = 1 (co-isometry, uses surjectivity)
    ext ψ
    -- Key insight: U(t) is surjective because U(-t) is a right inverse
    have h_surj : ∃ χ, U_grp.U t χ = ψ := by
      use U_grp.U (-t) ψ
      -- U(t)U(-t) = U(t + (-t)) = U(0) = 1
      have h := U_grp.group_law t (-t)
      simp only [add_neg_cancel] at h
      calc U_grp.U t (U_grp.U (-t) ψ)
          = U_grp.U (t + (-t)) ψ := by simp only [add_neg_cancel] ; rw [h]; exact rfl
        _ = U_grp.U 0 ψ := by ring_nf
        _ = ψ := by
          rw [@OneParameterUnitaryGroup.identity]
          exact rfl
    obtain ⟨χ, hχ⟩ := h_surj

    apply ext_inner_left ℂ
    intro φ
    simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply]
    -- Goal: ⟨φ, U(t) (U(t)* ψ)⟩ = ⟨φ, ψ⟩
    -- Write ψ = U(t)χ and use U(t)*U(t) = 1
    rw [← hχ]

    -- From Part 1, we have U(t)*U(t) = 1
    have h_first : (U_grp.U t).adjoint * U_grp.U t = 1 := by
      ext ξ
      apply ext_inner_left ℂ
      intro η
      simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply]
      rw [ContinuousLinearMap.adjoint_inner_right]
      exact h_inner η ξ

    -- Therefore U(t)*(U(t)χ) = χ
    have h_adj_apply : (U_grp.U t).adjoint (U_grp.U t χ) = χ := by
      have := congrFun (congrArg DFunLike.coe h_first) χ
      simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply] at this
      exact this

    -- Substitute: U(t)(U(t)*(U(t)χ)) = U(t)χ ✓
    rw [h_adj_apply]


/-- Time evolution preserves norms: ‖U(t)ψ‖ = ‖ψ‖.

**Physical meaning**: The total probability ‖ψ‖² is conserved under time evolution.
If a state is normalized (‖ψ‖ = 1), it remains normalized for all time.

**Proof**: Direct from the unitarity of U(t), which is encoded in `U_grp.unitary`.
The inner product ⟨U(t)ψ, U(t)ψ⟩ = ⟨ψ, ψ⟩ implies ‖U(t)ψ‖² = ‖ψ‖².

**Connection to §9-10**: This is the Hilbert space version of probability conservation.
In position space, ∫|ψ|² d³x is conserved (continuity equation). Here, ‖ψ‖² is
conserved in the abstract Hilbert space. They're the same statement in different
representations. -/
lemma unitary_preserves_norm (data : DiracSpectralData H) (t : ℝ) (χ : H) :
    ‖data.U_grp.U t χ‖ = ‖χ‖ := by
  have h_inner := data.U_grp.unitary t χ χ
  exact norm_preserving data.U_grp t χ

/-- **Electron number conservation**: ‖E₊ U(t) ψ‖ = ‖E₊ ψ‖.

**Physical meaning**: The probability of finding the particle in an electron state
(positive energy) is conserved under time evolution. If a state starts as 80%
electron and 20% positron, it stays that way forever.

**Why this is remarkable**: In non-relativistic QM, there's only one "species"
of particle. The Dirac equation has two sectors (electrons and positrons), and
this theorem says they don't mix under free evolution.

**Caveat**: This is for the FREE Dirac equation. With interactions (QED),
pair creation and annihilation CAN change electron/positron content. But for
the free equation, the split is preserved.

**Proof structure**:
1. E₊ and U(t) commute (both are functions of H_D)
2. Therefore E₊ U(t) ψ = U(t) E₊ ψ
3. U(t) preserves norms
4. So ‖E₊ U(t) ψ‖ = ‖U(t) E₊ ψ‖ = ‖E₊ ψ‖

**Connection to charge conservation**: In QFT, ‖E₊ψ‖² - ‖E₋ψ‖² is related to
electric charge. This theorem (combined with positron number conservation)
implies charge conservation for free Dirac particles. -/
theorem electron_number_conserved (data : DiracSpectralData H)
    (_ /-hm-/ : data.hamiltonian.constants.m > 0) (t : ℝ) (ψ : H)
    (hCommPos :
      data.U_grp.U t * data.E (Set.Ici data.hamiltonian.constants.restEnergy) =
      data.E (Set.Ici data.hamiltonian.constants.restEnergy) * data.U_grp.U t) :
    ‖electronProjection data (data.U_grp.U t ψ)‖ =
    ‖electronProjection data ψ‖ := by
  unfold electronProjection
  -- Step 1: E₊ and U(t) commute
  have h_op := unitary_commutes_with_spectral data t
                 (Set.Ici data.hamiltonian.constants.restEnergy) measurableSet_Ici hCommPos
  -- Step 2: Swap E₊ and U(t)
  have h_comm : data.E (Set.Ici data.hamiltonian.constants.restEnergy) (data.U_grp.U t ψ) =
                data.U_grp.U t (data.E (Set.Ici data.hamiltonian.constants.restEnergy) ψ) := by
    calc data.E _ (data.U_grp.U t ψ)
        = (data.E _ * data.U_grp.U t) ψ := rfl
      _ = (data.U_grp.U t * data.E _) ψ := by rw [h_op]
      _ = data.U_grp.U t (data.E _ ψ) := rfl
  -- Step 3: U(t) preserves norms
  rw [h_comm, unitary_preserves_norm]

/-- **Positron number conservation**: ‖E₋ U(t) ψ‖ = ‖E₋ ψ‖.

**Physical meaning**: The probability of finding the particle in a positron state
(negative energy) is conserved under time evolution.

**Historical note**: In Dirac's original "sea" picture, the negative energy states
are filled, and a "hole" (absence of a negative-energy electron) appears as a
positron with positive energy and positive charge. This conservation law says
the number of holes is constant — you can't spontaneously create or destroy
positrons without interactions.

**Modern interpretation**: The spectral projection E₋ simply picks out the
negative-energy part of the state. Conservation of ‖E₋ψ‖ means this component
evolves unitarily within its subspace, without leaking into the positive-energy
sector.

**Together with electron conservation**: Since E₊ + E₋ = 1 (for m > 0),
we have ‖E₊ψ‖² + ‖E₋ψ‖² = ‖ψ‖². Both terms are individually conserved,
which is stronger than just their sum being conserved.

**Proof**: Identical structure to `electron_number_conserved`, using E₋ = E((-∞, -mc²])
instead of E₊ = E([mc², ∞)). -/
theorem positron_number_conserved (data : DiracSpectralData H)
    (_ /-hm-/ : data.hamiltonian.constants.m > 0) (t : ℝ) (ψ : H)
    (hCommNeg :
      data.U_grp.U t * data.E (Set.Iic (-data.hamiltonian.constants.restEnergy)) =
      data.E (Set.Iic (-data.hamiltonian.constants.restEnergy)) * data.U_grp.U t) :
    ‖positronProjection data (data.U_grp.U t ψ)‖ =
    ‖positronProjection data ψ‖ := by
  unfold positronProjection
  -- Step 1: E₋ and U(t) commute
  have h_op := unitary_commutes_with_spectral data t
                 (Set.Iic (-data.hamiltonian.constants.restEnergy)) measurableSet_Iic hCommNeg
  -- Step 2: Swap E₋ and U(t)
  have h_comm : data.E (Set.Iic (-data.hamiltonian.constants.restEnergy)) (data.U_grp.U t ψ) =
                data.U_grp.U t (data.E (Set.Iic (-data.hamiltonian.constants.restEnergy)) ψ) := by
    calc data.E _ (data.U_grp.U t ψ)
        = (data.E _ * data.U_grp.U t) ψ := rfl
      _ = (data.U_grp.U t * data.E _) ψ := by rw [h_op]
      _ = data.U_grp.U t (data.E _ ψ) := rfl
  -- Step 3: U(t) preserves norms
  rw [h_comm, unitary_preserves_norm]


/-- **THE FIRST LAW EQUIVALENCE**: The fundamental theorem of quantum dynamics.

This structure encodes the equivalence between four pillars of quantum mechanics:

1. **Unitarity**: Time evolution preserves probability (U(t)*U(t) = 1)
2. **Self-adjointness**: The Hamiltonian is a physical observable (H* = H)
3. **Spectral invariance**: Energy probabilities are conserved (μ_{U(t)ψ} = μ_ψ)
4. **Energy conservation**: ⟨H⟩ is constant in time

**The logical web**:
    Self-adjointness
          ↓
    Stone's theorem
          ↓
      Unitarity ←――――――――→ Spectral invariance
          ↓                       ↓
   Norm preservation      Measure preservation
          ↓                       ↓
    Probability            Energy probability
    conservation             conservation
                                  ↓
                          Energy conservation


**Why "First Law"?**: In thermodynamics, the first law is energy conservation.
Here we have something deeper: not just that ⟨H⟩ is conserved, but that the
ENTIRE probability distribution over energies is conserved. This is the
spectral-theoretic generalization of the first law.

**Physical content**:
- Unitarity ensures probabilities sum to 1 and stay that way
- Self-adjointness ensures energy is measurable (real eigenvalues)
- Spectral invariance ensures energy measurements are reproducible
- Energy conservation is the familiar E = const

**Historical significance**: This equivalence was implicit in von Neumann's
formulation of quantum mechanics (1932) but the spectral measure perspective
makes it explicit. The Dirac equation is the first relativistic theory where
all four components hold simultaneously with a positive-definite probability. -/
structure FirstLawEquivalence {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (E : Set ℝ → H →L[ℂ] H)
    (hE : FunctionalCalculus.IsSpectralMeasureFor E gen) : Prop where
  /-- Time evolution is unitary: probability is conserved. -/
  unitary : ∀ t, Unitary (U_grp.U t)
  /-- The generator (Hamiltonian) is self-adjoint: energy is observable. -/
  selfAdjoint : gen.IsSelfAdjoint
  /-- **THE FIRST LAW**: The spectral measure is invariant under time evolution.
      This is the strongest form of energy conservation — not just ⟨H⟩, but
      the entire probability distribution over energies is preserved. -/
  spectral_invariant : ∀ t ψ B, MeasurableSet B →
    spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure B =
    spectral_scalar_measure E ψ hE.toIsSpectralMeasure B
  /-- Energy expectation is conserved: ⟨ψ(t)|H|ψ(t)⟩ = ⟨ψ(0)|H|ψ(0)⟩.
      This follows from spectral invariance as a special case. -/
  energy_conserved : ∀ t ψ (hψ : ψ ∈ gen.domain),
    ⟪gen.op ⟨U_grp.U t ψ, by exact gen.domain_invariant t ψ hψ⟩, U_grp.U t ψ⟫_ℂ = ⟪gen.op ⟨ψ, hψ⟩, ψ⟫_ℂ

/-- **Axiom**: Energy expectation equals the first moment of the spectral measure.

**Mathematical content**: ⟨ψ|H|ψ⟩ = ∫s dμ_ψ(s), where μ_ψ is the spectral
scalar measure associated to ψ.

**Physical interpretation**: The expected energy is the average over all
possible energy values, weighted by their probabilities. This is Born's rule
applied to energy measurements.

**Why an axiom?**: The proof requires:
1. Expressing H via functional calculus: H = ∫s dE(s)
2. Computing ⟨ψ|Hψ⟩ = ⟨ψ|∫s dE(s)ψ⟩ = ∫s d⟨ψ|E(s)ψ⟩ = ∫s dμ_ψ(s)

Step 2 involves interchanging inner products with spectral integrals, which
requires the full machinery of the spectral theorem for unbounded operators.

**Note**: This only makes sense for ψ in the domain of H (so Hψ is defined). -/
theorem energy_eq_spectral_moment {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (ψ : H) (hψ : ψ ∈ gen.domain)
    (h_energy : ⟪gen.op ⟨ψ, hψ⟩, ψ⟫_ℂ =
      ∫ s, s ∂(spectral_scalar_measure E ψ hE.toIsSpectralMeasure)) :
    ⟪gen.op ⟨ψ, hψ⟩, ψ⟫_ℂ = ∫ s, s ∂(spectral_scalar_measure E ψ hE.toIsSpectralMeasure) :=
  h_energy

/-- **MAIN THEOREM**: Self-adjointness implies the complete First Law equivalence.

**What this proves**: Starting from a self-adjoint generator H, we construct
the full `FirstLawEquivalence` structure, proving:
1. U(t) is unitary
2. H is self-adjoint (given)
3. Spectral measure is time-invariant
4. Energy expectation is conserved

**This is the culmination of the entire development**:
- §1-3: Built the Dirac matrices and operator
- §4-5: Established spectral properties (gap, unboundedness)
- §6: Connected to spectral framework
- §7: Showed relativistic dispersion relation
- §8-10: Proved probability conservation (spatial)
- §11: Proved probability conservation (spectral) — the First Law

**Proof strategy for each component**:

1. *Unitarity*: From inner product preservation (Stone's theorem).
   U(t)* U(t) = 1 follows from ⟨U(t)φ, U(t)ψ⟩ = ⟨φ, ψ⟩.
   U(t) U(t)* = 1 uses surjectivity (U(-t) is right inverse).

2. *Self-adjointness*: Given as hypothesis.

3. *Spectral invariance*: From `spectral_measure_invariant` (proven earlier).
   Uses [U(t), E(B)] = 0 (functional calculus commutes) and unitarity.

4. *Energy conservation*: From spectral invariance.
   ⟨H⟩ = ∫s dμ_ψ(s), and μ_{U(t)ψ} = μ_ψ, so ⟨H⟩ is constant.

**Physical significance**: This theorem says that a self-adjoint Hamiltonian
automatically gives you EVERYTHING: unitary evolution, conserved probabilities,
conserved energy, and conserved energy distribution. Self-adjointness is the
master key that unlocks quantum dynamics.

**For the Dirac equation specifically**: We have proven (axiomatically) that
H_D is essentially self-adjoint. This theorem then gives us all conservation
laws for free. Combined with the positive-definite probability density (§8),
we have a complete, consistent relativistic quantum mechanics. -/
theorem first_law_equivalence_of_self_adjoint {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (hComm : ∀ t B, MeasurableSet B → U_grp.U t * E B = E B * U_grp.U t)
    (hEnergyMoment : ∀ ψ (hψ : ψ ∈ gen.domain),
      ⟪gen.op ⟨ψ, hψ⟩, ψ⟫_ℂ = ∫ s, s ∂(spectral_scalar_measure E ψ hE.toIsSpectralMeasure)) :
    FirstLawEquivalence gen E hE where

  -- Component 1: Unitarity of U(t)
  unitary := fun t => by
    -- Inner product preservation from Stone's theorem
    have h_inner := U_grp.unitary t
    constructor
    · -- U(t)*U(t) = 1: isometry condition
      ext ψ
      apply ext_inner_left ℂ
      intro φ
      simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply]
      rw [ContinuousLinearMap.adjoint_inner_right]
      exact (h_inner φ ψ)
    · -- U(t)U(t)* = 1: co-isometry, requires surjectivity
      ext ψ
      -- U(-t) is a right inverse, so U(t) is surjective
      have h_surj : ∃ χ, U_grp.U t χ = ψ := by
        use U_grp.U (-t) ψ
        have h := U_grp.group_law t (-t)
        simp only [add_neg_cancel] at h
        calc U_grp.U t (U_grp.U (-t) ψ)
            = U_grp.U (t + (-t)) ψ := by simp only [add_neg_cancel] ; rw [h]; exact rfl
          _ = U_grp.U 0 ψ := by ring_nf
          _ = ψ := by rw [OneParameterUnitaryGroup.identity]; rfl
      obtain ⟨χ, hχ⟩ := h_surj
      apply ext_inner_left ℂ
      intro φ
      simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply]
      rw [← hχ]
      -- Use U(t)*U(t) = 1 from first part
      have h_first : (U_grp.U t).adjoint * U_grp.U t = 1 := by
        ext ξ
        apply ext_inner_left ℂ
        intro η
        simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply]
        rw [ContinuousLinearMap.adjoint_inner_right]
        exact (h_inner η ξ)
      have h_adj_apply : (U_grp.U t).adjoint (U_grp.U t χ) = χ := by
        have := congrFun (congrArg DFunLike.coe h_first) χ
        simp only [ContinuousLinearMap.mul_apply, ContinuousLinearMap.one_apply] at this
        exact this
      rw [h_adj_apply]

  -- Component 2: Self-adjointness (given)
  selfAdjoint := hsa

  -- Component 3: Spectral measure invariance (the First Law itself)
  spectral_invariant := fun t ψ B hB => spectral_measure_invariant gen hsa E hE t ψ B hB
    (hComm t B hB)

  -- Component 4: Energy conservation (consequence of spectral invariance)
  energy_conserved := by
    intro t ψ hψ
    -- Express energy expectation as spectral moment
    rw [hEnergyMoment (U_grp.U t ψ) (gen.domain_invariant t ψ hψ),
        hEnergyMoment ψ hψ]
    -- The spectral measures are equal by the First Law
    have h_measure_eq : spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure =
                        spectral_scalar_measure E ψ hE.toIsSpectralMeasure := by
      ext B hB
      exact spectral_measure_invariant gen hsa E hE t ψ B hB (hComm t B hB)
    -- Same measure ⟹ same integral
    rw [h_measure_eq]


/-- **Fundamental Equivalence**: Unitarity if and only if Spectral Invariance.

This is the central theorem of thermodynamic unitarity: a time evolution
preserves the spectral measure (energy probability distribution) if and
only if it is unitary.

**Physical meaning**: Unitarity isn't an arbitrary postulate — it's the
UNIQUE dynamics compatible with energy probability conservation. Any other
evolution would change the probability of measuring energy in some set B.

**Logical structure**:
  • Forward (spectral_measure_invariant): Unitarity ⟹ Spectral invariance
  • Backward (spectral_invariance_implies_unitary): Spectral invariance ⟹ Unitarity

**Analogy to classical mechanics**: This is the quantum Liouville theorem.
Classical Hamiltonian flow preserves phase space volume; quantum unitary
flow preserves spectral measure. Both are "the only dynamics consistent
with conservation." -/
theorem unitarity_iff_spectral_invariance {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (hComm : ∀ t B, MeasurableSet B → U_grp.U t * E B = E B * U_grp.U t) :
    (∀ t, Unitary (U_grp.U t)) ↔
    (∀ t ψ B, MeasurableSet B →
      spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure B =
      spectral_scalar_measure E ψ hE.toIsSpectralMeasure B) := by
  constructor
  · intro _ t ψ B hB
    exact spectral_measure_invariant gen hsa E hE t ψ B hB (hComm t B hB)
  · intro h_inv t
    exact spectral_invariance_implies_unitary gen E hE h_inv t

/-- **Charge Conservation**: The electric charge Q = ‖E₊ψ‖² - ‖E₋ψ‖² is time-invariant.

**Physical meaning**: In Dirac theory, electron number and positron number are
separately conserved (by `electron_number_conserved` and `positron_number_conserved`).
The electric charge, proportional to their difference, is therefore also conserved.

**Units**: In natural units with electron charge e = 1, this quantity IS the charge.
More precisely, Q = e·(N_electron - N_positron) where N are the "number operators"
given by ‖E_±ψ‖² for normalized ψ.

**Note**: This is for the FREE Dirac equation. In QED with interactions, virtual
pair creation can temporarily violate this, but the total charge of real particles
remains conserved by gauge invariance. -/
theorem charge_conserved (data : DiracSpectralData H)
    (hm : data.hamiltonian.constants.m > 0) (t : ℝ) (ψ : H)
    (hCommPos :
      data.U_grp.U t * data.E (Set.Ici data.hamiltonian.constants.restEnergy) =
      data.E (Set.Ici data.hamiltonian.constants.restEnergy) * data.U_grp.U t)
    (hCommNeg :
      data.U_grp.U t * data.E (Set.Iic (-data.hamiltonian.constants.restEnergy)) =
      data.E (Set.Iic (-data.hamiltonian.constants.restEnergy)) * data.U_grp.U t) :
    ‖electronProjection data (data.U_grp.U t ψ)‖^2 -
    ‖positronProjection data (data.U_grp.U t ψ)‖^2 =
    ‖electronProjection data ψ‖^2 - ‖positronProjection data ψ‖^2 := by
  rw [electron_number_conserved data hm t ψ hCommPos,
      positron_number_conserved data hm t ψ hCommNeg]

/-- **Spectral Moment Conservation**: All moments ⟨Hⁿ⟩ are time-invariant.

**Mathematical content**: ∫ sⁿ dμ_{U(t)ψ}(s) = ∫ sⁿ dμ_ψ(s) for all n ∈ ℕ.

**Physical meaning**:
  • n = 0: Total probability (normalization) is conserved
  • n = 1: Expected energy ⟨H⟩ is conserved (First Law, classical form)
  • n = 2: ⟨H²⟩ is conserved, hence variance (ΔH)² = ⟨H²⟩ - ⟨H⟩² is conserved
  • Higher n: All fluctuation statistics are frozen

**Why this matters**: The spectral measure μ_ψ is determined by its moments
(when they exist and satisfy Carleman's condition). So "all moments conserved"
is essentially equivalent to "measure conserved" — another view of the First Law.

**Proof**: The spectral measures are equal by `spectral_measure_invariant`,
so any integral against them is equal. -/
theorem spectral_moment_conserved {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (hComm : ∀ t B, MeasurableSet B → U_grp.U t * E B = E B * U_grp.U t)
    (n : ℕ) (t : ℝ) (ψ : H) :
    ∫ s, s^n ∂(spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure) =
    ∫ s, s^n ∂(spectral_scalar_measure E ψ hE.toIsSpectralMeasure) := by
  have h_measure_eq : spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure =
                      spectral_scalar_measure E ψ hE.toIsSpectralMeasure := by
    ext B hB
    exact spectral_measure_invariant gen hsa E hE t ψ B hB (hComm t B hB)
  rw [h_measure_eq]

/-- The energy variance (uncertainty squared) for a state.

    (ΔH)² = ⟨H²⟩ - ⟨H⟩² = ∫s² dμ - (∫s dμ)² -/
noncomputable def energyVariance {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (ψ : H) : ℝ :=
  (∫ s, s^2 ∂(spectral_scalar_measure E ψ hE.toIsSpectralMeasure)) -
  (∫ s, s ∂(spectral_scalar_measure E ψ hE.toIsSpectralMeasure))^2

/-- **Energy Uncertainty Conservation**: ΔH is time-invariant.

**Physical meaning**: The energy uncertainty of a state doesn't change under
time evolution. A state that starts with sharply defined energy stays sharp;
a state with large energy spread keeps that spread forever.

**Connection to energy-time uncertainty**: The relation ΔE·Δt ≥ ℏ/2 involves
the energy uncertainty ΔE = ΔH. This theorem says ΔE is constant, so the
"minimum time for state change" Δt ≥ ℏ/(2ΔE) is also a constant of motion.

**Proof**: Both ⟨H⟩ and ⟨H²⟩ are conserved (n=1 and n=2 moments), hence their
combination (ΔH)² = ⟨H²⟩ - ⟨H⟩² is conserved. -/
theorem energy_variance_conserved {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (hComm : ∀ t B, MeasurableSet B → U_grp.U t * E B = E B * U_grp.U t)
    (t : ℝ) (ψ : H) :
    energyVariance gen E hE (U_grp.U t ψ) = energyVariance gen E hE ψ := by
  unfold energyVariance
  have h1 := spectral_moment_conserved gen hsa E hE hComm 1 t ψ
  have h2 := spectral_moment_conserved gen hsa E hE hComm 2 t ψ
  simp only [pow_one] at h1
  rw [h1, h2]


/-- **Quantum Liouville Theorem**: The spectral measure is invariant under
Hamiltonian flow.

This is `spectral_measure_invariant` with a name emphasizing the classical
analogue:

  • Classical: Liouville's theorem says phase space volume ∫dᵈp dᵈq is
    preserved under Hamiltonian flow. Equivalently, the phase space
    density ρ(p,q) evolves as dρ/dt + {H,ρ} = 0.

  • Quantum: The spectral measure μ_ψ (probability distribution over
    energies) is preserved under unitary evolution. This is the
    spectral-theoretic analogue of Liouville's theorem.

Both say: "Hamiltonian dynamics preserves the natural measure." -/
theorem quantum_liouville {U_grp : OneParameterUnitaryGroup (H := H)}
    (gen : Generator U_grp) (hsa : gen.IsSelfAdjoint)
    (E : Set ℝ → H →L[ℂ] H) (hE : FunctionalCalculus.IsSpectralMeasureFor E gen)
    (hComm : ∀ t B, MeasurableSet B → U_grp.U t * E B = E B * U_grp.U t)
    (t : ℝ) (ψ : H) (B : Set ℝ) (hB : MeasurableSet B) :
    spectral_scalar_measure E (U_grp.U t ψ) hE.toIsSpectralMeasure B =
    spectral_scalar_measure E ψ hE.toIsSpectralMeasure B :=
  spectral_measure_invariant gen hsa E hE t ψ B hB (hComm t B hB)

end ThermodynamicUnitarity
