#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_FILE="${1:-docs/THEOREM_INDEX.md}"
TMP_FILE="$(mktemp)"
TMP_RAW="$(mktemp)"
trap 'rm -f "$TMP_FILE" "$TMP_RAW"' EXIT
PATTERN='^[[:space:]]*(theorem|lemma)[[:space:]]+[^[:space:]]+'

{
  echo "# Theorem Index"
  echo
  echo "Generated by \`tools/generate_theorem_index.sh\`."
  echo
  echo "| Name | Kind | File | Line | Layer |"
  echo "|---|---|---|---:|---:|"
} > "$OUT_FILE"

if command -v rg >/dev/null 2>&1; then
  set +e
  rg -n "$PATTERN" . \
    --glob '*.lean' \
    --glob '!.lake/**' \
    --glob '!scratch/**' \
    --glob '!Meta/**' \
    > "$TMP_RAW"
  SEARCH_STATUS=$?
  set -e

  if [[ "$SEARCH_STATUS" -ne 0 && "$SEARCH_STATUS" -ne 1 ]]; then
    exit "$SEARCH_STATUS"
  fi
else
  while IFS= read -r file; do
    set +e
    grep -nE "$PATTERN" "$file" | sed "s|^|./$file:|"
    SEARCH_STATUS="${PIPESTATUS[0]}"
    set -e

    if [[ "$SEARCH_STATUS" -ne 0 && "$SEARCH_STATUS" -ne 1 ]]; then
      exit "$SEARCH_STATUS"
    fi
  done < <(git ls-files '*.lean' | awk '$0 !~ /^scratch\// && $0 !~ /^Meta\//') > "$TMP_RAW"
fi

LC_ALL=C sort -t ':' -k1,1 -k2,2n "$TMP_RAW" > "$TMP_FILE"

awk -F: '
function layer_for(file, owner) {
  owner = file
  sub(/^\.\//, "", owner)
  if (index(owner, "/") > 0) {
    owner = substr(owner, 1, index(owner, "/") - 1)
  } else {
    sub(/\.lean$/, "", owner)
  }
  if (owner == "Mathematics" || owner == "Units") return "1"
  if (owner == "ClassicalInfo" || owner == "ClassicalMechanics" || owner == "Thermodynamics") return "2"
  if (owner == "Mechanics") return "3"
  if (owner == "SpaceAndTime") return "4"
  if (owner == "Electromagnetism" || owner == "Optics") return "5"
  if (owner == "Relativity") return "6"
  if (owner == "QuantumMechanics") return "7"
  if (owner == "QuantumInfo") return "8"
  if (owner == "QEC" || owner == "QFT") return "9"
  if (owner == "Particles") return "10"
  if (owner == "StatMech" || owner == "Cosmology" || owner == "CondensedMatter" || owner == "StringTheory") return "11"
  if (owner == "Physics") return "meta"
  if (owner == "Meta") return "tooling"
  if (owner == "Test") return "test"
  return "n/a"
}
{
  file = $1
  sub(/^\.\//, "", file)
  line = $2
  body = substr($0, index($0, $3))
  kind = "theorem"
  if (body ~ /^[[:space:]]*lemma[[:space:]]+/) kind = "lemma"
  name = body
  sub(/^[[:space:]]*(theorem|lemma)[[:space:]]+/, "", name)
  sub(/[[:space:]].*$/, "", name)
  gsub(/\|/, "\\\\|", name)
  printf("| `%s` | `%s` | `%s` | %s | %s |\n", name, kind, file, line, layer_for(file))
}' "$TMP_FILE" >> "$OUT_FILE"

echo "Wrote $OUT_FILE"
